[package]
name = "rust-hello-world"
version = "0.0.1"
authors = ["Cody P Schafer <dev@codyps.com>"]
repository = "https://github.com/frankplus/rust-hello-world"
edition = "2018"

[profile.release]
lto = true
panic = "abort"

